version: '3'

services:
  db:
    build:
      context: ./docker/db
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"

  php-fpm:
    build:
      context: docker/php-fpm
    depends_on:
        - db
    environment:
        - APP_SECRET=${APP_SECRET}
        - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:3306/${DATABASE_NAME}
        - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    volumes:
        - .:/var/www
    working_dir: /var/www

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "15672:15672"
